<?php

namespace ProcessWire;

/**
 * Mapping Engine for Data Migrator
 * Creates automatic field mappings based on analysis results
 */
class MappingEngine extends WireData {

    /**
     * Create automatic mapping from analysis results
     *
     * @param array $analysis Table analysis from DataAnalyzer
     * @param string $tableName Original table name
     * @param string|null $titleFieldOverride Optional: Override the title field
     * @return array Mapping configuration
     */
    public function createMapping($analysis, $tableName, $titleFieldOverride = null) {
        // Validate required analysis fields
        if (!isset($analysis['suggested_template']) || !isset($analysis['columns'])) {
            throw new \Exception('Invalid analysis data structure. Missing required fields.');
        }

        // FIX: Handle null suggested_title_field - use override or find fallback
        $titleField = $titleFieldOverride ?? $analysis['suggested_title_field'] ?? null;

        // If still null, try to find a suitable fallback
        if (!$titleField) {
            // First: look for common title field names
            $commonTitleNames = ['title', 'name', 'headline', 'subject', 'label', 'titel', 'bezeichnung'];
            foreach ($analysis['columns'] as $col) {
                if (in_array(strtolower($col['name']), $commonTitleNames)) {
                    $titleField = $col['name'];
                    break;
                }
            }
        }

        if (!$titleField) {
            // Second: use first non-ID string/text field
            foreach ($analysis['columns'] as $col) {
                if (!$col['is_likely_id'] && in_array($col['base_type'], ['string', 'text'])) {
                    $titleField = $col['name'];
                    break;
                }
            }
        }

        if (!$titleField) {
            // Last resort: use first non-ID field of any type
            foreach ($analysis['columns'] as $col) {
                if (!$col['is_likely_id']) {
                    $titleField = $col['name'];
                    break;
                }
            }
        }

        if (!$titleField) {
            throw new \Exception('No suitable title field found and none specified. Please select a title field manually.');
        }

        $mapping = [
            'table_name' => $tableName,
            'template' => $analysis['suggested_template'],
            'parent' => '/imports/' . $analysis['suggested_template'] . 's/',
            'title_field' => $titleField,
            'name_field' => null, // Auto-generate from title
            'fields' => [],
            'skip_fields' => ['id', 'name'], // Skip system fields (auto-generated by ProcessWire)
        ];

        // Map each column to a ProcessWire field
        foreach ($analysis['columns'] as $column) {
            $columnName = $column['name'];

            // Skip system fields (ID, name, etc.)
            if ($column['is_likely_id'] || in_array(strtolower($columnName), $mapping['skip_fields'])) {
                continue;
            }

            // Create field mapping
            $fieldMapping = [
                'source_column' => $columnName,
                'target_field' => $this->sanitizeFieldName($columnName, $mapping['template']),
                'fieldtype' => $column['suggested_fieldtype'],
                'label' => $this->generateLabel($columnName),
                'required' => !$column['nullable'],
                'confidence' => $column['detection_confidence'],
            ];

            // Add type-specific options
            if ($column['suggested_fieldtype'] === 'FieldtypeOptions' && isset($column['options'])) {
                $fieldMapping['options'] = $column['options'];
            }

            $mapping['fields'][$columnName] = $fieldMapping;
        }

        return $mapping;
    }

    /**
     * Sanitize column name to valid ProcessWire field name
     * IMPORTANT: Fields are prefixed with template name to ensure uniqueness across tables
     */
    protected function sanitizeFieldName($name, $templateName) {
        // Convert to lowercase
        $name = strtolower($name);

        // Replace invalid characters with underscore
        $name = preg_replace('/[^a-z0-9_]/', '_', $name);

        // Remove consecutive underscores
        $name = preg_replace('/_+/', '_', $name);

        // Trim underscores
        $name = trim($name, '_');

        // Check for ProcessWire reserved field names
        $reserved = [
            'id', 'name', 'parent', 'parent_id', 'parents', 'template', 'template_id',
            'templates', 'children', 'child', 'created', 'modified', 'createdUser',
            'modifiedUser', 'sort', 'sortfield', 'numChildren', 'num_children',
            'url', 'path', 'httpUrl', 'httpurl', 'status', 'references', 'rootParent',
            'description', // Page description meta field
        ];

        // If field name is reserved, prefix with "field_"
        if (in_array($name, $reserved)) {
            $name = 'field_' . $name;
        }

        // Ensure it doesn't start with a number
        if (preg_match('/^\d/', $name)) {
            $name = 'field_' . $name;
        }

        // CRITICAL: Sanitize template name to remove hyphens (ProcessWire field names can't have hyphens)
        // Template names use hyphens, but field names must use underscores only
        $templatePrefix = str_replace('-', '_', $templateName);

        // CRITICAL: Prefix with template name to make fields unique per table
        // This prevents conflicts when multiple tables have same column names
        // e.g., orders.status and customers.status become orders_status and customers_status
        $name = $templatePrefix . '_' . $name;

        return $name;
    }

    /**
     * Generate human-readable label from column name
     */
    protected function generateLabel($name) {
        // Replace underscores with spaces
        $label = str_replace('_', ' ', $name);

        // Uppercase first letter of each word
        $label = ucwords($label);

        return $label;
    }

    /**
     * Validate mapping configuration
     *
     * @param array $mapping Mapping configuration
     * @return array Validation result
     */
    public function validateMapping($mapping) {
        $errors = [];
        $warnings = [];

        // Check template name
        if (empty($mapping['template'])) {
            $errors[] = 'Template name is required';
        }

        // Check parent path
        if (empty($mapping['parent'])) {
            $errors[] = 'Parent path is required';
        }

        // Check title field
        if (empty($mapping['title_field'])) {
            $warnings[] = 'No title field specified - will use first text field';
        }

        // Check field mappings
        if (empty($mapping['fields'])) {
            $errors[] = 'No field mappings defined';
        }

        return [
            'valid' => empty($errors),
            'errors' => $errors,
            'warnings' => $warnings,
        ];
    }

    /**
     * Get mapping summary for display
     *
     * @param array $mapping Mapping configuration
     * @return array Summary information
     */
    public function getMappingSummary($mapping) {
        $fieldCount = count($mapping['fields']);
        $requiredFields = 0;
        $optionalFields = 0;

        foreach ($mapping['fields'] as $field) {
            if ($field['required']) {
                $requiredFields++;
            } else {
                $optionalFields++;
            }
        }

        return [
            'template' => $mapping['template'],
            'parent' => $mapping['parent'],
            'title_field' => $mapping['title_field'],
            'field_count' => $fieldCount,
            'required_fields' => $requiredFields,
            'optional_fields' => $optionalFields,
        ];
    }
}
